CREATE APPLICATION ROLE IF NOT EXISTS appn_role;

CREATE OR ALTER VERSIONED SCHEMA code;
GRANT USAGE ON SCHEMA code TO APPLICATION ROLE appn_role;

CREATE STREAMLIT IF NOT EXISTS code.streamlit
    FROM '/'
    MAIN_FILE = 'streamlit.py'
    TITLE = 'Streamlit Native App';
GRANT USAGE ON STREAMLIT code.streamlit
    TO APPLICATION ROLE appn_role;
